name: 🚀 test and publish

on:
  push:
    branches: 
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: npm install, and test
        run: |
          npm ci
          npm test -- --verbose

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions: 
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Check version changes
  #       uses: EndBug/version-check@v2
  #       id: check

  #     - name: Version update detected
  #       if: steps.check.outputs.changed == 'true'
  #       run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

  #     - name: Use Node.js 16
  #       if: steps.check.outputs.changed == 'true'
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com
  #         scope: '@jellycat-js'

  #     - name: Download build artifact
  #       if: steps.check.outputs.changed == 'true'
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: rollup artifacts
  #         path: dist

  #     - name: Publish package to Github Package Registry
  #       if: steps.check.outputs.changed == 'true'
  #       run: npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}